-- MySQL Script generated by MySQL Workbench
-- Mon Jun 25 19:56:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tacodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tacodb` ;

-- -----------------------------------------------------
-- Schema tacodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tacodb` DEFAULT CHARACTER SET utf8mb4 ;
USE `tacodb` ;

-- -----------------------------------------------------
-- Table `tacodb`.`taco`
-- -----------------------------------------------------
create table if not exists `tacodb`.`taco` (
`id` int not null AUTO_INCREMENT,
`name` varchar(50) not null,
`createdAt` timestamp not null,
PRIMARY KEY (`id`))
ENGINE = InnoDB;


create table if not exists `tacodb`.`Ingredient` (
`id` varchar(4) not null,
`name` varchar(25) not null,
`type` varchar(10) not null,
PRIMARY KEY (`id`))
ENGINE = InnoDB;


create table if not exists `tacodb`.`Taco_Ingredients` (
`tacoId` int not null,
`ingredientId` varchar(4) not null)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use tacodb;
insert into Ingredient (id, name, type)
values ('FLTO', 'Flour Tortilla', 'WRAP');
insert into Ingredient (id, name, type)
values ('COTO', 'Corn Tortilla', 'WRAP');
insert into Ingredient (id, name, type)
values ('GRBF', 'Ground Beef', 'PROTEIN');
insert into Ingredient (id, name, type)
values ('CARN', 'Carnitas', 'PROTEIN');
insert into Ingredient (id, name, type)
values ('TMTO', 'Diced Tomatoes', 'VEGGIES');
insert into Ingredient (id, name, type)
values ('LETC', 'Lettuce', 'VEGGIES');
insert into Ingredient (id, name, type)
values ('GOUD', 'Goudse kaas', 'CHEESE');
insert into Ingredient (id, name, type)
values ('CHED', 'Cheddar', 'CHEESE');
insert into Ingredient (id, name, type)
values ('JACK', 'Monterrey Jack', 'CHEESE');
insert into Ingredient (id, name, type)
values ('SLSA', 'Salsa', 'SAUCE');
insert into Ingredient (id, name, type)
values ('SRCR', 'Sour Cream', 'SAUCE');

